# Project name
PROGRAM = baka

# Source code directory
SOURCE_DIR = ./src

# Build directory
BUILD_DIR = ./build

# Subdirectory for the release binary
RELEASE_DIR = $(BUILD_DIR)/release

# Subdirectory for the debug binary
DEBUG_DIR = $(BUILD_DIR)/debug

# List of all source files
SOURCE_FILES = $(wildcard $(SOURCE_DIR)/*.c)

# List of object files
RELEASE_OBJECTS = $(patsubst $(SOURCE_DIR)/%.c, $(RELEASE_DIR)/%.o, $(SOURCE_FILES))
DEBUG_OBJECTS = $(patsubst $(SOURCE_DIR)/%.c, $(DEBUG_DIR)/%.o, $(SOURCE_FILES))

# Any dependent header files
DEPS =

# Any special libraries (needed for build)
LIBS = -lcurses

# Any special header files (needed for build)
INCLUDES =

# Set the compiler
CC = gcc
CC_DEBUG = gcc

# Set any compiler flags
CFLAGS = -std=c99 -Wall -Wextra -O2 -pedantic
CFLAGS_DEBUG = -std=c99 -Wall -Wextra -O0 -g -pedantic

# baka specific variables
# values will be expanded by the shell, so variable like HOME can be used...
BAKA_HOME = $${HOME}/.baka
BAKA_CONFIG = $${HOME}/.baka/config
BAKA_SCRIPT = $${HOME}/bin/baka
